### ISSUE TITLE
Firmware Changes to fix software shutdown timing and other improvements

### ISSUE THREAD

**Issue by hoopsurfer** [hoopsurfer/pidesktop#13]
Requested firmware for STM8S MCU to address firmware issues from Embest - no reponse to date.

Ideas:
1) Make software shutdown (OS initiated) as fast has button push - need to signal MCU to do the same as button press initiated shutdown
2) Support "press press" reboot to allow button initiated reboot

Note MCU is STM8S005CK part, 8-bit controller with 32Kb flash plus 128 bytes EEPROM, 2Kb RAM onboard pins are labeled for programming MCU.

**Comment by hoopsurfer** [comment]
I have purchased a STM8S development board to start reverse engineering the firmware, if anyone has STM8 experience or wants to help let me know!

**Comment by hoopsurfer** [comment]
I've been able to convince the Support team at Embest Technologies to provide sources rather than have me continue decompiling the code.  I've stopped that work now that I have the sources and have them building now.

**Comment by TiceRex** [comment]
Do you have any progress?
I guess you are not allowed to share the source code of the factory firmware, but I would be glad to help you.

**Comment by hoopsurfer** [comment]
While I have the firmware rewritten, I've decided not to publish/support it because RP4 is taking such a different direction, you can find the source code for the firmware in this repo:

https://github.com/hoopsurfer/mcu-power-control/tree/master/Pi_Desktop_iap_Stm8

**Comment by TiceRex** [comment]
Actually, I don't have RPi3 and PiDesktop anymore, I also went for RPi4.
Anyway, thank you for the support so far. Best wishes!
