### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jernst** [hoopsurfer/pidesktop#16]
(I also filed this upstream:https://github.com/pi-desktop/deb-make/issues/8 )

What is the license for this code? I cannot find a LICENSE.txt or license header in the files.

Given how it has been published, and the installation instructions that come with the Pi Desktop, I will assume that you intended to put this code in the public domain or use a common open-source license. Please advise if this is not correct.

**Comment by hoopsurfer** [comment]
I've applied the MIT license, thanks for asking.
