### ISSUE TITLE
Reboot on Pi 3B not working

### ISSUE THREAD

**Issue by robynjayqueerie** [hoopsurfer/pidesktop#18]
Thank you for cleaning up this Pi Desktop. I was struggling with the original before I found your fork.
Just one issue that I can see. I started with a Pi 3B and the Desktop. Eventually I did get the latest Raspian Stretch installed on a SSD and got it booting up without SD card. I installed the pidesktop as instructed from the .deb file. Whenever I use Reboot from the GUI Shutdown menu, it goes through the exercise of 30 seconds of flashing then shuts down. If I replace the Pi 3B with a Pi 3B+ the reboot function works as expected. I am using a cheaper Vaseky 1.8" 32GB MSATA drive but I don't think that is the issue as the Pi 3B+ works fine.  BTW a sudo reboot shows the same behaviour on both Pi's
Do you have any ideas?
Thanks

**Comment by hoopsurfer** [comment]
Can you provide the output of pd-check?  Reboot from the menu or the command line should work exactly the same.  For me with a 3B or 3B+ reboot either way takes just seconds before the Pi Desktop top LED stops flashing.

First thing I would check is if you have the latest Raspian Stretch kernel and matching firmware via `pd-check` and you should see dates after March.  If you see March or earlier you should:

`sudo apt update`
`sudo apt full-upgrade`

And try `pd-check` again to see the new dates.

**Comment by hoopsurfer** [comment]
Here is what I see:

 OS & Firmware versions:

raspberrypi-firmware soc:firmware: Attached to firmware from 2018-04-16 18:16
Linux 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 GNU/Linux

**Comment by robynjayqueerie** [comment]
Hi, sorry for the delay, I have been trying to get node and sqlite working

 

I have attached the output from the pd-check, it has not line breaks but hopefully you will find what you want.

 

It was all the latest stretch Raspbian installed and pd-check shows todays date

 

Kind regards

Robyn

 

 

Robyn Hannah PhD BE (Hons 1) Grad Dip Counselling.

 <http://nrie.com.au/NRIEWB9Version/index.html> NRIE Logo

NRI Electronics Pty. Ltd.

PO Box 20, Alstonville, NSW, 2477.

Phone: 02 6628 7961 or 0427 068 257

email:  <mailto:contact@nrie.com.au> mailto:contact@nrie.com.auWeb www.nrie.com.au

**Comment by hoopsurfer** [comment]
It looks like you have the correct firmware, I'm expecting when you say it works with the 3B+ you are using the same mSATA SSD with the exact same raspian image on it just changing the underlying board correct?

IF that is true, one possibility is you have /boot/config.txt setup to be board specific, check to make sure this line is in your config.txt and it is not specific to any one model using what are called section headers.  You should see the gpio option in your config.txt and it must be executed to turn off the flashing from the power management controller (else it shuts the system down after ~30 seconds as you are seeing)  

`gpio=6=op,pn,dl`

When this happens during boot (early stage boot), it causes the case top LED to stop flashing.  I will do some retesting on a 3B myself when I get a chance.

**Comment by robynjayqueerie** [comment]
Yes, all I am doing is swapping the underlying board from a 3B to a 3B+

I will run the thing up and do the tests on Monday, thanks for your help

Robyn

 

 

Robyn Hannah PhD BE (Hons 1) Grad Dip Counselling.

 <http://nrie.com.au/NRIEWB9Version/index.html> NRIE Logo

NRI Electronics Pty. Ltd.

PO Box 20, Alstonville, NSW, 2477.

Phone: 02 6628 7961 or 0427 068 257

email:  <mailto:contact@nrie.com.au> mailto:contact@nrie.com.auWeb www.nrie.com.au

**Comment by robynjayqueerie** [comment]
Just checked, the config.txt is attached, it looks as you are expecting it.

Robyn

 

Robyn Hannah PhD BE (Hons 1) Grad Dip Counselling.

 <http://nrie.com.au/NRIEWB9Version/index.html> NRIE Logo

NRI Electronics Pty. Ltd.

PO Box 20, Alstonville, NSW, 2477.

Phone: 02 6628 7961 or 0427 068 257

email:  <mailto:contact@nrie.com.au> mailto:contact@nrie.com.auWeb www.nrie.com.au

**Comment by robynjayqueerie** [comment]
Interesting, if I run the unit up and do a reboot it works, reboots fine but then second time always goes to shutdown.

Robyn

 

 

Robyn Hannah PhD BE (Hons 1) Grad Dip Counselling.

 <http://nrie.com.au/NRIEWB9Version/index.html> NRIE Logo

NRI Electronics Pty. Ltd.

PO Box 20, Alstonville, NSW, 2477.

Phone: 02 6628 7961 or 0427 068 257

email:  <mailto:contact@nrie.com.au> mailto:contact@nrie.com.auWeb www.nrie.com.au

**Comment by hoopsurfer** [comment]
Are you seeing any LEDs blink on the Pi board?  If that still won't boot, perhaps try:

`sudo touch /forcefsck`

And shutdown/start to repair a possible damaged boot partition.  I have seen reboot failures from crashes and from my observations the 3B+ appears to be more sensitive.

**Comment by hoopsurfer** [comment]
Another approach to force fsck at boot is to add the following to /boot/config.txt and just comment them when not needed.  I have seen both the `sudo touch /forcefsck` and this approach fix a system that didn't boot.

`fsck,mode=force`
`fsck.repair=yes`

more info at: https://www.freedesktop.org/software/systemd/man/systemd-fsck@.service.html

**Comment by robynjayqueerie** [comment]
Thanks, I will try it, sorry to have been a bit slack on this, there has been so much to do here. I will report the results

Robyn

 

 

Robyn Hannah PhD BE (Hons 1) Grad Dip Counselling.

 <http://nrie.com.au/NRIEWB9Version/index.html> NRIE Logo

NRI Electronics Pty. Ltd.

PO Box 20, Alstonville, NSW, 2477.

Phone: 02 6628 7961 or 0427 068 257

email:  <mailto:contact@nrie.com.au> mailto:contact@nrie.com.auWeb www.nrie.com.au

**Comment by hoopsurfer** [comment]
If you updated to firmware dated 2018-06-29 or later then you have a specific reboot fix that would explain the improvement, otherwise what I've found is there are some Pi devices that tend to work on boot (without that new fix) and some that do not.   Glad it is working for you.
