### ISSUE TITLE
Freeze/Lockup using PI 3 Model B+

### ISSUE THREAD

**Issue by TurboGez** [hoopsurfer/pidesktop#28]
When I am booting from MSATA on a Pi 3 Model B+ I am getting a frozen screen after about 30 to 60 mins.  Seems to be related to the hardware for MSATA as I get this before and after I install the PI desktop software. Anyone else getting this on a 3B+?  I see one user reported in another forum Element14 says that this case does not support the 3B+.

**Comment by hoopsurfer** [comment]
I would check your power supply, instability is common with marginal power.  A clear sign on a 3B+ is a yellow lightning bolt on the screen.
