### ISSUE TITLE
Power-Key thinks button is always pressed.

### ISSUE THREAD

**Issue by opjose** [hoopsurfer/pidesktop#31]
I want to run this script on a PI equipped with the 735 ver 2.1 and an 825 in the Geekworm metal case.

When I install the package and reboot, the system shuts down after a few seconds.
When I pull the MicroSD card I can see in the logs that the PI thinks the button is being pressed.
I see the messages from the powerkey.py script in the logs indicating a 5 second press.

However if I run the original Geekworm script for the 735 this does not happen.

Any idea as to what I can change to fix this?

Thanks for writing this btw!

**Comment by hoopsurfer** [comment]
Ah, the pidesktop project does not support the 735, use my pdx project which does. https://github.com/hoopsurfer/pdx
